/**  *****************************************************************************
	LAB 1
  *******************************************************************************

////// The above comment is automatically generated by CoIDE ///////////////////

#include "stm32f4xx.h"
#include "stm32f4xx_gpio.h"
#include "stm32f4xx_rcc.h"
#define LED1 GPIOD, GPIO_Pin_12
#define LED2 GPIOD, GPIO_Pin_13
#define LED3 GPIOD, GPIO_Pin_14
#define LED4 GPIOD, GPIO_Pin_15
#define button GPIOA, GPIO_Pin_0
int a, b, c, d ;
GPIO_InitTypeDef GPIO_InitStruct;
static void GPIO_setup(void)
{RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOD, ENABLE);
	GPIO_InitStruct.GPIO_Pin = GPIO_Pin_15 | GPIO_Pin_14 | GPIO_Pin_13 | GPIO_Pin_12; // we want to configure all LED GPIO pins
		GPIO_InitStruct.GPIO_Mode = GPIO_Mode_OUT; 		// we want the pins to be an output
		GPIO_InitStruct.GPIO_Speed = GPIO_Speed_50MHz; 	// this sets the GPIO modules clock speed
		GPIO_InitStruct.GPIO_OType = GPIO_OType_PP; 	// this sets the pin type to push / pull (as opposed to open drain)
		GPIO_InitStruct.GPIO_PuPd = GPIO_PuPd_NOPULL; 	// this sets the pullup / pulldown resistors to be inactive
		GPIO_Init(GPIOD, &GPIO_InitStruct);
}

static void button_setup(void)
{RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);
	GPIO_InitStruct.GPIO_Pin = GPIO_Pin_0;		  // we want to configure PA0
		GPIO_InitStruct.GPIO_Mode = GPIO_Mode_IN; 	  // we want it to be an input
		GPIO_InitStruct.GPIO_Speed = GPIO_Speed_50MHz;//this sets the GPIO modules clock speed
		GPIO_InitStruct.GPIO_OType = GPIO_OType_PP;   // this sets the pin type to push / pull (as opposed to open drain)
		GPIO_InitStruct.GPIO_PuPd = GPIO_PuPd_DOWN;   // this enables the pulldown resistor --> we want to detect a high level
		GPIO_Init(GPIOA, &GPIO_InitStruct);
}
int main(void){
	GPIO_setup();
	button_setup();
	GPIO_ResetBits(GPIOD, GPIO_Pin_12 | GPIO_Pin_13 |GPIO_Pin_14 |GPIO_Pin_15 );

while(1)
{

loop:	if(GPIO_ReadInputDataBit(button == 1)  ) //Ambil Data Bit Button
		{a++;

			while(GPIO_ReadInputDataBit(button == 1)) //Selama Belum Dilepas Loop Terus
			{}
		}

	if (a==1)
		{GPIO_SetBits(LED2); // LED1 ON
		GPIO_ResetBits(GPIOD,  GPIO_Pin_13 |GPIO_Pin_14 |GPIO_Pin_15 ); //LED off
		}

	if (a==2)
			{GPIO_SetBits(LED1); // LED1 ON
			GPIO_ResetBits(GPIOD,  GPIO_Pin_12 |GPIO_Pin_14 |GPIO_Pin_15 ); //LED off
			}
	if (a==3)
				{GPIO_SetBits(LED3); // LED1 ON
				GPIO_ResetBits(GPIOD,  GPIO_Pin_12 |GPIO_Pin_13 |GPIO_Pin_15 ); //LED off
				}
	if (a==4)
				{GPIO_SetBits(LED4); // LED1 ON
				GPIO_ResetBits(GPIOD,  GPIO_Pin_12 |GPIO_Pin_13 |GPIO_Pin_14 ); //LED off
				}
	if (a==5)
	{a=1;}
}
}
*/

/*
 * ==========================================================
 * LAB 2
 * =========================================================
 */ 

#include "stm32f4xx.h"
#include "stm32f4xx_gpio.h"
#include "stm32f4xx_rcc.h"
#include "stm32f4xx_tim.h"
#include "misc.h"
#define LED1 GPIOD, GPIO_Pin_12
#define LED2 GPIOD, GPIO_Pin_13
#define LED3 GPIOD, GPIO_Pin_14
#define LED4 GPIOD, GPIO_Pin_15
#define button GPIOA, GPIO_Pin_0

GPIO_InitTypeDef GPIO_InitStruct;
void
INTTIM_Config(void);
void
GPIO_Config(void);

void highlightLed(int i)
{
	switch(i)
	{
		case 0: {
			GPIO_SetBits(LED1); // LED1 ON
			GPIO_ResetBits(GPIOD,  GPIO_Pin_13 |GPIO_Pin_14 |GPIO_Pin_15 ); //LED off
		} break;
		case 1: {
			GPIO_SetBits(LED2); // LED1 ON
			GPIO_ResetBits(GPIOD,  GPIO_Pin_13 |GPIO_Pin_14 |GPIO_Pin_15 ); //LED off
		} break;
		case 2: {
			GPIO_SetBits(LED3); // LED1 ON
			GPIO_ResetBits(GPIOD,  GPIO_Pin_13 |GPIO_Pin_14 |GPIO_Pin_15 ); //LED off
		} break;
		case 3: {
			GPIO_SetBits(LED4); // LED1 ON
			GPIO_ResetBits(GPIOD,  GPIO_Pin_13 |GPIO_Pin_14 |GPIO_Pin_15 ); //LED off
		} break;
	}
}

void getTimer()
{
}

int main(void)
{
GPIO_Config();
INTTIM_Config();
 while(1)
 {
//	 while(TIM2->CNT < 1000)
//	 {
//		 if(TIM2->CNT == 200)
//		 {
//		 GPIO_SetBits(LED2); // LED1 ON
//		 GPIO_ResetBits(GPIOD,  GPIO_Pin_13 |GPIO_Pin_14 |GPIO_Pin_15 ); //LED off
//		 }
//		 else if (TIM2->CNT == 500)
//		 {
//			 GPIO_SetBits(LED1); // LED1 ON
//			 GPIO_ResetBits(GPIOD,  GPIO_Pin_13 |GPIO_Pin_14 |GPIO_Pin_15 ); //LED off
//		 }
//	 }
 }
}
void TIM2_IRQHandler(void)
{
	if (TIM_GetITStatus(TIM2, TIM_IT_Update) != RESET)
	{
		TIM_ClearITPendingBit(TIM2, TIM_IT_Update);
		GPIOD->ODR ^= GPIO_Pin_13;
	}
	else
	{
		highlightLed(0);
	}
//GPIOD->ODR ^= GPIO_Pin_13;
//highlightLed(0);
//highlightLed(1);
//highlightLed(2);
//highlightLed(3);


}
void GPIO_Config(void) {
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOD, ENABLE);
		GPIO_InitStruct.GPIO_Pin = GPIO_Pin_15 | GPIO_Pin_14 | GPIO_Pin_13 | GPIO_Pin_12; // we want to configure all LED GPIO pins
			GPIO_InitStruct.GPIO_Mode = GPIO_Mode_OUT; 		// we want the pins to be an output
			GPIO_InitStruct.GPIO_Speed = GPIO_Speed_50MHz; 	// this sets the GPIO modules clock speed
			GPIO_InitStruct.GPIO_OType = GPIO_OType_PP; 	// this sets the pin type to push / pull (as opposed to open drain)
			GPIO_InitStruct.GPIO_PuPd = GPIO_PuPd_NOPULL; 	// this sets the pullup / pulldown resistors to be inactive
			GPIO_Init(GPIOD, &GPIO_InitStruct);
}
void INTTIM_Config(void)
{
NVIC_InitTypeDef nvic_struct;
nvic_struct.NVIC_IRQChannel = TIM2_IRQn;
nvic_struct.NVIC_IRQChannelPreemptionPriority
= 0; nvic_struct.NVIC_IRQChannelSubPriority
= 1; nvic_struct.NVIC_IRQChannelCmd =
ENABLE;
NVIC_Init(&nvic_struct);
TIM_TimeBaseInitTypeDef tim_struct;
RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM2, ENABLE);
tim_struct.TIM_Period = 10000 - 1;
tim_struct.TIM_Prescaler = 1680-1;
tim_struct.TIM_ClockDivision = 0;
//tim_struct.TIM_Period = 5;
//tim_struct.TIM_Prescaler = 1;
//tim_struct.TIM_ClockDivision = 0;
tim_struct.TIM_CounterMode = TIM_CounterMode_Up;
TIM_TimeBaseInit(TIM2, &tim_struct);
TIM_ITConfig(TIM2, TIM_IT_Update, ENABLE);
TIM_Cmd(TIM2,
ENABLE);
}
